[package]
name = "sound-prust"
version = "0.1.0"
authors = ["toumarihikana"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
conrod_glium = "0.70.0"
glium = "0.27.0"